services:
  pgbouncer:
    image: edoburu/pgbouncer
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    ports:
      - "5432:5432"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=db
    # ports:
    # - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis-stack:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_ARGS=--requirepass redis_password
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
